server:
  port: 8081
  mode: release

mysql:
  host: mysql
  port: 3307
  username: root
  password: 1234
  dbname: feed_video
  charset: utf8mb4

redis:
  host: redis
  port: 6380
  password: ""
  db: 0

kafka:
  brokers:
    - kafka:9092

jwt:
  secret: "a9f3kLm92Jd8sKqP0xZr7Tn4WbC6Yh1V"
  expire_hours: 72

upload:
  base_path: /app/storage
  avatar_dir: avatar
  cover_dir: cover
  video_dir: video
